refactor: tests with uv

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -23,7 +23,6 @@ jobs:
         run: uv sync --locked --all-extras --dev
 
       - name: Run tests
-        # For example, using `pytest`
         run: | 
           # If there is not tests, then skip
-          uv run --locked --all-extras --dev -m pytest
+          uv run --locked --all-extras --dev -m pytest || (echo "uv run failed, running pytest directly" && pytest)
